rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
script: "bundle exec rspec"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphviz
env:
  - PUPPET_VERSION=2.6.18
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.2
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.18
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.18
